version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "dev-awsconnect-extensions"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-8tmxm5gtwykk"
s3_prefix = "dev-awsconnect-extensions"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ConnectParam=\"arn:aws:connect:us-east-1:828393986024:instance/794790f5-0ae2-4348-806a-f58bf245ab3f\" TableParam=\"agent-directory\" BucketParam=\"agent-directory\""
image_repositories = []
