AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Globals:
Description: SAM deployment of agent extension system for Amazon Connect
Metadata:
Parameters:
  ConnectParam:
    Description: Enter the ARN of the Amazon Connect Instance.
    Type: String
  BucketParam:
    Description: Enter the name of the bucket for csv export.
    Type: String
Conditions:
Resources:
  UpdateAgentDbLamda:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: awsconnect-extensions/
      Description: Lambda to update agent extension database for Amazon Connect
      Environment: 
        Variables: 
          CONNECT_IID :  
            Ref: ConnectParam
          TABLE_NAME: AgentData
          BUCKET_NAME:
            Ref: BucketParam
      Events:
        AgentDBSchedule:
          Type: Schedule
          Properties: 
            Schedule: 'rate(1 hour)'
            Name: AgentDBSchedule
            Description: Updates Agent Database
            Enabled: true
      FunctionName: UpdateAgentDb
      Handler: update_db.lambda_handler
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
          TableName: AgentData
        - S3WritePolicy:
          TableName:
            Ref: BucketParam
        - Statement:
          - Sid: ConnectListUsers
          Effect: Allow
          Action:
            - connect:ListUsers
          Resource:
            Ref: ConnectParam
      Runtime: python3.9
      Timeout: 600
  GetAgentLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: awsconnect-extensions/
      Description: Lambda to update agent extension database for Amazon Connect
      FunctionName: GetAgent
      Handler: getAgent.lambda_handler
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
          TableName: AgentData
      Runtime: python3.9
      Timeout: 5
  AgentData:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
        - AttributeName: sk_value
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: skIndex
          KeySchema:
            - AttributeName: sk
              KeyType: HASH
            - AttributeName: sk_value
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      TableName: AgentData
